const kaiba = [
  {
    id: "23995346",
    name: "Blue-Eyes Ultimate Dragon",
    att: 4500,
    def: 3800,
    pos: "FACE",
    place: "DECK",
    image: "/images/cards/kaiba_deck/23995346.jpg",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "89631139",
    name: "Blue-Eyes White Dragon",
    att: 3000,
    def: 2500,
    pos: "FACE",
    place: "DECK",
    image: "images/cards/kaiba_deck/89631139.jpg",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "2111707",
    name: "XY-Dragon Cannon",
    att: 2200,
    def: 1900,
    pos: "FACE",
    place: "DECK",
    image: "/images/cards/kaiba_deck/2111707.jpg",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "5053103",
    name: "Battle Ox",
    att: 1700,
    def: 1000,
    place: "DECK",
    image: "/images/cards/kaiba_deck/5053103.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "10000000",
    name: "Obelisk the Tormentor",
    att: 4000,
    def: 4000,
    place: "DECK",
    image: "/images/cards/kaiba_deck/10000000.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "14898066",
    name: "Vorse Raider",
    att: 1900,
    def: 1200,
    place: "DECK",
    image: "/images/cards/kaiba_deck/14898066.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "17444133",
    name: "Kaiser Sea Horse",
    att: 1700,
    def: 1650,
    place: "DECK",
    image: "/images/cards/kaiba_deck/17444133.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "17658803",
    name: "Luster Dragon",
    att: 2400,
    def: 1400,
    place: "DECK",
    image: "/images/cards/kaiba_deck/17658803.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "17985575",
    name: "Lord of D.",
    att: 1200,
    def: 1100,
    place: "DECK",
    image: "/images/cards/kaiba_deck/17985575.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "22804644",
    name: "Doom Virus Dragon",
    att: 1900,
    def: 1500,
    place: "DECK",
    image: "/images/cards/kaiba_deck/22804644.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "24611934",
    name: "Ryu-Kishin Powered",
    att: 1600,
    def: 1200,
    place: "DECK",
    image: "/images/cards/kaiba_deck/24611934.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "25119460",
    name: "YZ-Tank Dragon",
    att: 2100,
    def: 2200,
    place: "DECK",
    image: "/images/cards/kaiba_deck/25119460.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  // {
  //   id: "25119460",
  //   name: "YZ-Tank Dragon",
  //   att: 2100,
  //   def: 2200,
  //   place: "DECK",
  //   image: "/images/cards/kaiba_deck/25119460.jpg",
  //   pos: "FACE",
  //   hasAttacked: false,
  //   hasChangedPosition: false,
  // },
  {
    id: "31553716",
    name: "Spear Dragon",
    att: 1900,
    def: 0,
    place: "DECK",
    image: "/images/cards/kaiba_deck/31553716.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },

  {
    id: "39507162",
    name: "Blade Knight",
    att: 1600,
    def: 1000,
    place: "DECK",
    image: "/images/cards/kaiba_deck/39507162.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  // {
  //   id: "43586926",
  //   name: "Twin-Headed Behemoth",
  //   att: 1500,
  //   def: 1200,
  //   place: "DECK",
  //   image: "/images/cards/kaiba_deck/43586926.jpg",
  //   pos: "FACE",
  //   hasAttacked: false,
  //   hasChangedPosition: false,
  // },

  {
    id: "43586926",
    name: "Twin-Headed Behemoth",
    att: 1500,
    def: 1200,
    place: "DECK",
    image: "/images/cards/kaiba_deck/43586926.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "50939127",
    name: "Different Dimension Dragon",
    att: 1200,
    def: 1500,
    place: "DECK",
    image: "/images/cards/kaiba_deck/50939127.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "58293343",
    name: "Tyrant Burst Dragon",
    att: 2900,
    def: 2500,
    place: "DECK",
    image: "/images/cards/kaiba_deck/58293343.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "62651957",
    name: "X-Head Cannon",
    att: 1800,
    def: 1500,
    place: "DECK",
    image: "/images/cards/kaiba_deck/62651957.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "64500000",
    name: "Z-Metal Tank",
    att: 1500,
    def: 1300,
    place: "DECK",
    image: "/images/cards/kaiba_deck/64500000.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "65622692",
    name: "Y-Dragon Head",
    att: 1500,
    def: 1600,
    place: "DECK",
    image: "/images/cards/kaiba_deck/65622692.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "73398797",
    name: "Paladin of White Dragon",
    att: 1900,
    def: 1200,
    place: "DECK",
    image: "/images/cards/kaiba_deck/73398797.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "81985784",
    name: "Des Feral Imp",
    att: 1600,
    def: 1800,
    place: "DECK",
    image: "/images/cards/kaiba_deck/81985784.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  // {
  //   id: "82301904",
  //   name: "Chaos Emperor Dragon-Envoy of the End",
  //   att: 3000,
  //   def: 2500,
  //   place: "DECK",
  //   image: "/images/cards/kaiba_deck/82301904.jpg",
  //   pos: "FACE",
  //   hasAttacked: false,
  //   hasChangedPosition: false,
  // },
  {
    id: "82301904",
    name: "Chaos Emperor Dragon-Envoy of the End",
    att: 3000,
    def: 2500,
    place: "DECK",
    image: "/images/cards/kaiba_deck/82301904.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "91998121",
    name: "XYZ-Dragon Cannon",
    att: 2800,
    def: 2600,
    place: "DECK",
    image: "/images/cards/kaiba_deck/91998121.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
  {
    id: "99724761",
    name: "XZ-Tank Cannon",
    att: 2400,
    def: 2100,
    place: "DECK",
    image: "/images/cards/kaiba_deck/99724761.jpg",
    pos: "FACE",
    hasAttacked: false,
    hasChangedPosition: false,
  },
];

export const decks = [kaiba];
